spring:
  application:
    name: lzs-chat
  profiles:
    active: dev
server:
  port: 7777
  thymeleaf:
    prefix: 'classpath:/templates'
    suffix: .html
    cache: false
  tomcat:
    max-threads: 500
    min-spare-threads: 10
  connection-timeout: 5000

mybatis-plus:
  #
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  typeAliasesPackage: com.lzs
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql